# Impact 

<!-- **Instructions**
Please address these specific points:

- How sustainable is the proposed project inside the ETH Domain?

- To what extent will the planned project substantially advance the ORD field, or solve a critical outstanding problem in the targeted field(s)?

- To what extent does the proposal support a collaborative approach,
  involving significant synergies, complementarities, or/and scientific
  added-value to achieve its objectives? -->


It is particularly important for not only to solve a critical problem in our community, but also to do so in sustainable manner. We are convinced that aligning the *Open Time Series* project with the FAIR principles [@fair] is instrumental in establishing our approach in our own community and reaching other research communities. 

## Sustainability in the ETH Domain

Pushing an ORD approach at the KOF Swiss Economic Institute, which has a leading role in the field of economics in Switzerland and is an important monitor of the Swiss economy, will help advance ORD practices in empirical economics and official statistics in the long term. 
The use of the *Open Time Series* framework in teaching and monitoring work that involves official statistics will help the digital transformation process in official statistics through the education of future researchers and public servants who become familiar with Swiss official statistics data and ORD principles alike. 
In addition, our inclusive approach helps to keep the community involved, while the idea of modular software packages with maintainers at the dataset level allows hand over maintenance responsibilities in case of changes in personnel.
The Comprehensive R Archive Network (CRAN) and the R Project for Statistical Computing have a long tradition at ETH.
The ETH domain and its staff contributed substantially to the language and its extension packages, including to CRAN itself^[see also https://stat.ethz.ch/CRAN/ accessed on February 12, 2024]. 

## Solving a Critical Problem

Although there has been a certain sense of urgency for digital transformation in the public sector at least since the pandemic, change management within large institutions does not always align with the timeline of individual academic careers or ongoing daily business. 
While we greatly appreciate advances in making official statistics available through application programming interfaces (API), as well as investment into community exchange, we provide an immediate solution to data sourcing to those that need to source public data today. 
In addition, we help identify redundant efforts across institutions and broker the usage of common sources which entails using public money more efficiently. 
Finally, we help bridge the gap and strengthen the link between public administration and academic research. Our addition of time series to the Swiss data landscape lifts the state-of-the-art by facilitating intertemporal comparison and real-time analysis.



## Collaborative Approach

The proposed *Open Time Series* project is highly collaborative in multiple ways. 
The technical approach is inclusive and modular. Through open-sourcing and focusing on the core package, we hold ourselves accountable through the community and, at the same time, encourage contribution to the technical core. 
In our data provider-specific modules, we foster collaboration at the dataset level.
Through our own dataset modules, we provide examples that collaborators from other fields can use -- along with the documentation -- as blueprints to build their own extension packages to process data from their respective fields. 
Finally, we involve data providers from the very start of the project.
Our goal is to use our traditional ties with federal and regional public administration to establish a channel for hands-on, two-way feedback between data providers and the research community.
In the process, we plan to take part in existing academic and non-academic community events and explore new ways and formats, particularly in a kind of teaching that involves students in our collaborative approach. 


## FAIR Principles 

The *Open Time Series* project aims at making its output **findable**. 
We combine our own experience with the expertise and reach of our partners to find the optimal outlets to help us reach multiple communities.
A high degree of automation allows us to consider and maintain multiple platforms, from GitHub to CRAN for our software and from Dryad^[https://datadryad.org/stash accessed on February 12, 2024] to opendata.swiss and Zenodo^[https://zenodo.org/ accessed on February 12, 2024] for our datasets.  
As stated before, we intend to subject our work to a scientific software review [@review] by the renowned rOpenSci [@ropensci] organization.

>rOpenSci fosters a culture that values open and reproducible research using shared data and reusable software -- https://ropensci.org/about/, accessed on February 12, 2024.

We make our work **accessible**. With the support of ETH Legal Services, we will open-source our software and will find appropriate open-source and creative common licenses for our software and data. 

We will not make any compromise when it comes to making our data **interoperable**.
We will build on the World Wide Web Consortium's (W3C) idea of CSV on the Web^[see also https://csvw.org/ accessed on February 12, 2024], setting the tone for interoperability. Like CSVW, our data output will split data and metadata into two files: a data CSV file and a metadata JSON file. We will use standard CSV files for time series to not only allow virtually any programming language to process them but also ensure that standard office software can read our data. 
Our JSON metadata files extend the basic idea of the W3C. We will use a key to refer to data and allow the storage of comprehensive, multilingual meta-information. 

A **reusable** and extendable framework and data pool of macroeconomic time series will be a core contribution of the *Open Time Series* project. We will not only provide the data and software as is; we will also provide community support on our GitHub page and Research Software Engineering and Economic Data (RSEED) matrix chat space. In addition, we use the project as a teaching example and ambassador for the FAIR principles among ETH students. 


